databases:
  - name: kanbanApp_DB
    databaseName: 「Info内のConnectionsにあるDatabase」を入れる
    user: kanbanApp
    region: singapore

services:
  - type: web
    name: kanbanApp
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kanbanApp_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
